/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.lospapus.vistas;

import com.lospapus.basededatos.conexionBD;
import java.awt.Color;

/**
 *
 * @author nchig
 */
public class JPanelPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form JPanelAgregar
     */
    public JPanelPrincipal() {
        initComponents();
        VerificarConexion();
    }

        private void VerificarConexion() {
        conexionBD conexionBD = new conexionBD();
        boolean conexionExitosa = conexionBD.verificarConexion(); // Cambiado a un método estático
        if (conexionExitosa) {
            lblEstadoConexion.setText("Conectado");
            lblEstadoConexion.setForeground(Color.GREEN);
        } else {
            lblEstadoConexion.setText("No conectado");
            lblEstadoConexion.setForeground(Color.RED);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblEstadoConexion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(560, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(570, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 184, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Bienvenidos al ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 560, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 184, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("inventario DuocUC");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 560, 60));

        jLabel2.setForeground(new java.awt.Color(255, 184, 0));
        jLabel2.setText("Estado con la base de dato:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 256, -1, -1));

        lblEstadoConexion.setForeground(new java.awt.Color(255, 255, 255));
        lblEstadoConexion.setText("jLabel3");
        jPanel1.add(lblEstadoConexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 256, -1, -1));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 452, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 184, 0));
        jLabel4.setText("Hecho por: Nicolas Hernandez, Hans Mancilla y Nicolas Chiguay");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 484, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEDE.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 520));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEstadoConexion;
    // End of variables declaration//GEN-END:variables
}
