/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.lospapus.vistas;

import javax.swing.JOptionPane;
import com.lospapus.basededatos.conexionBD;
import com.lospapus.controlador.ControladorAgregar;
import java.awt.event.KeyEvent;
import javax.swing.ButtonGroup;
import javax.swing.JTextField;

/**
 *
 * @author nchig
 */
public class JPanelAgregar extends javax.swing.JPanel {
    
    ControladorAgregar controlador;

    /**
     * Creates new form JPanelAgregar
     */
    public JPanelAgregar() {
        initComponents();
        initStyles();
        controlador = new ControladorAgregar(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initStyles() {
        textfieldNombreProducto.putClientProperty("JTextField.placeholderText", "Ej: Papas grandes");
        textfieldPrecioProducto.putClientProperty("JTextField.placeholderText", "Ej: 1500");
        textfieldCantidadProducto.putClientProperty("JTextField.placeholderText", "Ej: 20");

    }

    public int getCantidadProducto() {
        return Integer.parseInt(textfieldCantidadProducto.getText());
    }

    public String getNombreProducto() {
        return textfieldNombreProducto.getText();
    }

    public double getPrecioProducto() {
        return Double.parseDouble(textfieldPrecioProducto.getText());
    }

    public int getTipoProducto() {
        int opcion = 0;
        if (this.rbtnBebida.isSelected()) {
            opcion = 1;
        } else if (this.rbtnComida.isSelected()) {
            opcion = 2;
        }
        return opcion;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoProducto = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelNombreProducto = new javax.swing.JLabel();
        textfieldNombreProducto = new javax.swing.JTextField();
        labelPrecioProducto = new javax.swing.JLabel();
        textfieldPrecioProducto = new javax.swing.JTextField();
        labelCantidadProducto = new javax.swing.JLabel();
        textfieldCantidadProducto = new javax.swing.JTextField();
        rbtnBebida = new javax.swing.JRadioButton();
        rbtnComida = new javax.swing.JRadioButton();
        labelCategoriaProducto = new javax.swing.JLabel();
        btnSubir = new javax.swing.JToggleButton();
        Clear = new javax.swing.JButton();

        setForeground(new java.awt.Color(1, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(560, 500));

        labelNombreProducto.setForeground(new java.awt.Color(255, 255, 255));
        labelNombreProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreProducto.setText("Nombre del Producto");

        textfieldNombreProducto.setForeground(new java.awt.Color(255, 255, 255));

        labelPrecioProducto.setForeground(new java.awt.Color(255, 255, 255));
        labelPrecioProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPrecioProducto.setText("Precio del Producto");

        textfieldPrecioProducto.setForeground(new java.awt.Color(255, 255, 255));
        textfieldPrecioProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfieldPrecioProductoKeyTyped(evt);
            }
        });

        labelCantidadProducto.setForeground(new java.awt.Color(255, 255, 255));
        labelCantidadProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCantidadProducto.setText("Cantidad del Producto");

        textfieldCantidadProducto.setForeground(new java.awt.Color(255, 255, 255));
        textfieldCantidadProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfieldCantidadProductoKeyTyped(evt);
            }
        });

        tipoProducto.add(rbtnBebida);
        rbtnBebida.setForeground(new java.awt.Color(255, 255, 255));
        rbtnBebida.setText("Bebida");
        rbtnBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnBebidaActionPerformed(evt);
            }
        });

        tipoProducto.add(rbtnComida);
        rbtnComida.setForeground(new java.awt.Color(255, 255, 255));
        rbtnComida.setText("Comida");

        labelCategoriaProducto.setForeground(new java.awt.Color(255, 255, 255));
        labelCategoriaProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCategoriaProducto.setText("Categoria del Producto");

        btnSubir.setText("Subir a la base de datos");
        btnSubir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubirMouseClicked(evt);
            }
        });
        btnSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActionPerformed(evt);
            }
        });

        Clear.setText("Limpiar");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtnBebida)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnComida))
                            .addComponent(labelCategoriaProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNombreProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPrecioProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCantidadProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textfieldCantidadProducto)
                            .addComponent(textfieldPrecioProducto)
                            .addComponent(textfieldNombreProducto, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(13, 13, 13)))
                .addGap(198, 198, 198))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(241, 241, 241))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(labelNombreProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfieldNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelPrecioProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfieldPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCantidadProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfieldCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelCategoriaProducto)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnBebida)
                    .addComponent(rbtnComida))
                .addGap(18, 18, 18)
                .addComponent(btnSubir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Clear)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnBebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnBebidaActionPerformed

    private void btnSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubirActionPerformed

    private void btnSubirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubirMouseClicked
        // TODO add your handling code here:
        if (textfieldNombreProducto == null || textfieldCantidadProducto == null || textfieldPrecioProducto == null || (!rbtnBebida.isSelected() && !rbtnComida.isSelected())) {
            JOptionPane.showMessageDialog(null, "los campos no pueden quedar vacios.!");
        } else {
            controlador.agregarProductos();
        }


    }//GEN-LAST:event_btnSubirMouseClicked

    private void textfieldPrecioProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldPrecioProductoKeyTyped
        // TODO add your handling code here:
        //Restringir a solo numeros
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_textfieldPrecioProductoKeyTyped

    private void textfieldCantidadProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldCantidadProductoKeyTyped
        // TODO add your handling code here:
        //Restringir a solo numeros
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_textfieldCantidadProductoKeyTyped

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        textfieldNombreProducto.setText("");
        textfieldPrecioProducto.setText("");
        textfieldCantidadProducto.setText("");
        tipoProducto.clearSelection();
    }//GEN-LAST:event_ClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JToggleButton btnSubir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCantidadProducto;
    private javax.swing.JLabel labelCategoriaProducto;
    private javax.swing.JLabel labelNombreProducto;
    private javax.swing.JLabel labelPrecioProducto;
    private javax.swing.JRadioButton rbtnBebida;
    private javax.swing.JRadioButton rbtnComida;
    private javax.swing.JTextField textfieldCantidadProducto;
    private javax.swing.JTextField textfieldNombreProducto;
    private javax.swing.JTextField textfieldPrecioProducto;
    private javax.swing.ButtonGroup tipoProducto;
    // End of variables declaration//GEN-END:variables
}
